openapi: 3.0.0
info:
  title: Orzu Landing
  version: 1.0.0
tags:
  - name: Ping Pong!
    description: Check status of server
  # - name: Info
  #   description: Information
  - name: Application
    description: Application
  - name: Merchant
    description: Merchant
servers:
  - url: /orzu
  - url: /

paths:
  /landing/ping:
    get:
      tags:
      - Ping Pong!
      summary: Ping
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
                example:
                  message: "success"
                  payload: Backend orzu landing pong!

  # /landing/getInfo:
  #   get:
  #     tags:
  #     - Info
  #     summary: Getting Info
  #     description: <h1>Obtaining data at the first loading of the main page.</h1>
  #     responses:
  #       "200":
  #         description: Information successfully received
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               x-content-type: application/json
  #             example:
  #               message: success
  #               payload:
  #                 limit: 50000
  #       "500":
  #         description: Internal Server Error
  #         content:
  #           application/json:
  #             schema:
  #               type: object
  #               x-content-type: application/json
  #               example:
  #                 message: internal server error 
  #                 payload: null

  /landing/sendApplication:
    post:
      tags:
      - Application
      summary: Accepting the application followed by sending an OTP code.
      requestBody:  
        description: |-
          # Getting application data <br/>
          ### Type of client = user:
          ```
            {
              "type_of_client": "user",
              "full_name": "123",
              "phone": "123411178",
              "city": "ac",
              "application_type": "asdgf"
            }
          ```
          ### Type of client = merchant:
          ```
            {
              "type_of_client": "merchant",
              "full_name": "asd",
              "company_name": "dsd",
              "address": "qwe",
              "phone": "123479111",
              "industry": "asd"
            }
          ```
        required: true
        content:
          application/json:
            schema:
              type: object 
              required:
                - full_name
                - phone
                - city
                - application_type
                - t
              properties:
                type_of_client:
                  type: string
                  example: user
                full_name:
                  type: string
                  example: Jhon Cena Abdusatorovich
                phone:
                  type: string
                  example: 123456789
                city:
                  type: string
                  example: Душанбе
                application_type:
                    type: string
                    example: Оформление орзу
      responses:
        "200":
          description: Application sent successfully
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: success
                payload: null
        "400":
          description:
            One of
            <li> bad request </li> <br>
            <li> Неверный формат телефонного номера </li> <br>
            <li> Одно или несколько полей пустые </li> <br>
            <li> Вам следует правильно заполнить все поля </li> <br>
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: bad request
                payload: null
        "419":
          description: Retry limit exceeded
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: Превышен лимит повторных попыток
                payload: null
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: internal server error 
                payload: null
            
  /landing/checkOtp:
    get:
      tags:
      - Application
      summary: Checking otp code
      description: <h1>Checking the received code for authenticity</h1>
      parameters:
        - in: query
          required: true
          name: phone
          description: The phone to which the code was sent
          schema:
            type: string
            example: 123456789
        - in: query
          required: true
          name: code
          schema:
            type: string
            example: 1234
          description: Received code
      responses:
        "200":
          description: The code is genuine
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: success
                payload: null
        "400":
          description:
            One of
            <li> bad request </li> <br>
            <li> Одно или несколько полей пустые </li> <br>
            <li> Неправильный код otp </li> <br>
            <li> Вам следует правильно заполнить все поля </li> <br>
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: bad request
                payload: null
        "419":
          description: Retry limit exceeded
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: Превышен лимит повторных попыток
                payload: null
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: internal server error 
                payload: null

  /landing/getMerchantList:
    get:
      tags:
      - Merchant
      summary: Getting a list of merchants
      description: <h1>Getting a list of merchants</h1>
      parameters:
        - in: query
          name: search
          description: Search text for future filtering
          schema:
            type: string
            example: Burger king 
        - in: query
          required: false
          name: city
          description: The name of the city for future filtering
          schema:
            type: string
            example: Душанбе
        - in: query
          required: false
          name: category
          description: Сategory id for future filtering
          schema:
            type: integer
            example: 2
        - in: query
          required: false
          name: page
          description: Page of pagination
          schema:
            type: integer
            example: 2
        - in: query
          required: false
          name: pageLimit
          description: Limit of pagination
          schema:
            type: integer
            example: 2
      responses:
        "200":
          description: Merchant list successfully received
          content:
            application/json:
              schema:
                type: object
                x-content-type: application/json
              example:
                message: success
                payload:
                  maxPage: 1
                  merchantsList:
                  - id: 1
                    logo:
                    name: Жорик
                  - id: 2
                    logo:
                    name: Клавиатура
                  - id: 3
                    logo:
                    name: Паришь
                  - id: 4
                    logo:
                    name: Бургеры халал

components:
  schemas:
    UserApplication:
      type: object
      required:
        - full_name
        - phone
        - city
        - application_type
      properties:
        full_name:
          type: string
        phone: 
          type: string
          minLength: 9
          maxLength: 9
        city:
          type: string
          enum: []
        application_type: 
          type: string
          enum: [Оформление орзу, Повысить лимит орзу]
    MerchantApplication:
      type: object
      required:
        - full_name
        - company_name
        - address
        - phone
        - industry
      properties:
        full_name:
          type: string
        phone: 
          type: string
          minLength: 9
          maxLength: 9
        address:
          type: string
        company_name: 
          type: string
        industry:
          type: string
    Merchant:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        category:
          type: string
        logo:
          type: string
        city: 
          type: string
        affiliates:
          type: array
          items:
            type: object
            properties:
              address: 
                type: string
              contact:
                type: string
        commissions:
          type: array
          items:
            type: object
            properties:
              date: 
                type: number
              commission:
                type: integer